### ISSUE TITLE
mod causes game to stop responding

### ISSUE THREAD

**Issue by ITSLOCKED** [BrianComics/Minecraft-Mods#2]
I recently installed the mod to find out whenever I reach certain points when I drop down into a cave the game immediately stops responding and I'm forced to close it using task manager the issue stopped when I removed the mod

**Comment by BrianComics** [comment]
Thank you for bringing this to my attention. Does it generate any crash reports?

**Comment by BrianComics** [comment]
I have fixed the bug in Sparkle v1.0.1. You can download it right now on Modrinth or wait for the CurseForge version to get reviewed.
